name: Build
on:
  push:
    branch: main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi


    - name: Z88DK Toolchain setup
      run: |
        sudo snap install z88dk --edge

    - name: Create build directory
      run: |
        mkdir build

    - name: Run CMake
      run: |
        cmake ..
      working-directory: build

    - name: Build with make
      run: |
        make
      working-directory: build